apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hollow-pinniped-go 
  janus-idp.io/tekton: hollow-pinniped-go
  backstage.io/kubernetes-id: hollow-pinniped-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hollow-pinniped-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  