apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hollow-pinniped-go-gitops
  description: This is GitOps manifest for hollow-pinniped-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: hollow-pinniped-go
    janus-idp.io/tekton: hollow-pinniped-go 
    backstage.io/kubernetes-id: hollow-pinniped-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:hollow-pinniped-go
