apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hollow-pinniped-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hollow-pinniped-go 
  name: hollow-pinniped-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hollow-pinniped-go 
